### ISSUE TITLE
Remove conditional compilation

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#51]
Examine uses of conditional compilation (e.g. ARCH_NAME, ISSUE_123_DISABLE_FIX, etc.) and eliminate where possible.

**Comment by broskoTT** [comment]
Conditional compilation for ARCH_NAME was removed by @tt-vjovanovic a while back. But it still remains in CMakeLists.
Make sure to remove it as part of this task.

**Comment by joelsmithTT** [comment]
The `DISABLE_ISSUE_3487_FIX` define can be made a runtime thing.  Here's additional context for that issue:
https://yyz-gitlab.local.tenstorrent.com/tenstorrent/syseng/-/issues/3487
https://yyz-gitlab.local.tenstorrent.com/tenstorrent/syseng/-/merge_requests/1149/diffs

**Comment by broskoTT** [comment]
Is this issue now complete? I do see some isolated cases of ifdefs, but looks like the two top offenders are now resolved? What do you think @joelsmithTT @pjanevskiTT

**Comment by pjanevskiTT** [comment]
As for as umd_device target, I think it is complete. However, we still have tests. I am working on removing soc descriptor from tt_SiliconDevice constructor, after that we can have unified compilation for tests as well

**Comment by joelsmithTT** [comment]
The code part is more or less complete (no more ARCH_NAME in source files) but as @pjanevskiTT points out there is still a bit more work to do for the tests.  (ARCH_NAME still shows up in tests/CMakeLists.txt and controls include paths).

**Comment by blozano-tt** [comment]
Speaking of tests:

- I think we still need to get rid of ARCH_NAME ENV

I think we have a few options, but the easiest that is coming to mind is some CMake magic to generate 3x the number of executables. 

i.e. a custom add_executable

umd_add_exectuable(target_name arch_name)

Use the above in a for each loop.

cc: @afuller-TT

**Comment by blozano-tt** [comment]
```
function(umd_add_executable target arch interface_lib)
    # Create the executable target
    add_executable(${target})

    # Link the interface library to the new target
    target_link_libraries(${target} PRIVATE ${interface_lib})

    # Set the compile definitions based on the architecture
    if(${arch} STREQUAL "ARCH1")
        target_compile_definitions(${target} PRIVATE DEFINE_ARCH1)
        target_include_directories(${target} PRIVATE ${CMAKE_SOURCE_DIR}/path/to/include_arch1)
    elseif(${arch} STREQUAL "ARCH2")
        target_compile_definitions(${target} PRIVATE DEFINE_ARCH2)
        target_include_directories(${target} PRIVATE ${CMAKE_SOURCE_DIR}/path/to/include_arch2)
    elseif(${arch} STREQUAL "ARCH3")
        target_compile_definitions(${target} PRIVATE DEFINE_ARCH3)
        target_include_directories(${target} PRIVATE ${CMAKE_SOURCE_DIR}/path/to/include_arch3)
    else()
        message(FATAL_ERROR "Unknown architecture: ${arch}")
    endif()
endfunction()
```

**Comment by afuller-TT** [comment]
@blozano-tt 
> I think we have a few options, but the easiest that is coming to mind is some CMake magic to generate 3x the number of executables.

Executable?  or lib?
If the arch logic is all pushed down to a lib that we load a runtime, then everything everywhere could be a single executable, right?

If this is actual _unit_ tests (no hw involved) then doing a matrix of tests in a single executable would suffice, no?

**Comment by blozano-tt** [comment]
> Executable? or lib? If the arch logic is all pushed down to a lib that we load a runtime, then everything everywhere could be a single executable, right?

I was talking about all the test exes, unfortunately the test cases need to be ARCH_NAME aware.

> If this is actual _unit_ tests (no hw involved) then doing a matrix of tests in a single executable would suffice, no?

I am not familiar with all the tests in the repo, but there are at least some that require hardware.

**Comment by pjanevskiTT** [comment]
@blozano-tt @afuller-TT can you open smaller issues for separate tests where the aim would be to remove conditional compilation and close this bigger issue?

**Comment by broskoTT** [comment]
Closed in favor of #270  capturing further progress
